version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123Mudar!"
    volumes:
#      - ./postgresData/:/docker-entrypoint-initdb.d/01-basegeografica.sql
#      - ./postgresData/:/docker-entrypoint-initdb.d/02-basegeografica.sql
      - ./postgresData:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
     image: redis:6.0.7
     container_name: redis
     restart: always
     volumes:
       - redis_volume_data:/data
     ports:
     - 7001:6379
  redis_insight:
     image: redislabs/redisinsight:latest
     container_name: redis_insight
     restart: always
     ports:
       - 5500:8001
     volumes:
     - redis_insight_volume_data:/db

volumes:
  redis_volume_data:
  redis_insight_volume_data: